import settings as ENV
from Client.bom_the_bot import BOMTHEBOT

print("ACIVATE_MESSAGE =", ENV.ACIVATE_MESSAGE)
print("ALLOW_CHANNELS =",ENV.ALLOW_CHANNELS)
print("BOT_NOI_TOKEN =", ENV.BOT_NOI_TOKEN)
print("DISCORD_TOKEN =", ENV.DISCORD_TOKEN)
print("CHATBOT_STYLE =", ENV.CHATBOT_STYLE)
print("HEADERS =", ENV.HEADERS)

bot = BOMTHEBOT()
bot.run(ENV.DISCORD_TOKEN)
